# we have to make sure that the disk is NOT mounted by cloud-init beforehand
- name: mount ephemeral disk
  mount:
    path: /vol/scratch
    src: "{{ ephemerals[0] }}"
    fstype: ext4
    state: mounted
  when:
    - ephemerals

- name: Change permissions for mountpoint
  file:
    path: /vol/scratch
    mode: 0777
    state: directory
    recurse: yes