- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present


- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present
  vars:
    arch_mapping:
      x86_64: amd64

- name: Install Docker
  apt:
    name:
      - docker.io
      - python3-docker
      - docker-compose
      - docker-compose-plugin
    state: present
  tags: install

- name: Configure Docker
  copy:
    content: |-
      {
         "mtu":{{ ansible_default_ipv4.mtu }}
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0o644"
  notify: Docker

- name: Create docker group and change GID
  group:
    name: docker
    gid: 1234
    state: present

- name: Append ubuntu user to group docker
  user:
    name: ubuntu
    append: true
    groups: docker
