- name: Create system overrides directories (slurmctld)
  file:
    path: "/etc/systemd/system/slurmctld.service.d"
    group: root
    owner: root
    mode: "0o755"
    state: directory

- name: Copy system overrides (slurmctld)
  copy:
    src: "slurm/systemd/slurmctld.override"
    dest: "/etc/systemd/system/slurmctld.service.d/override.conf"
    mode: "0o644"
    owner: root
    group: root

- name: Change group ownership of OpenStack credentials file to slurm if it exists
  block:
    - name: Check if the OpenStack credentials file exists
      stat:
        path: /etc/openstack/clouds.yaml
      register: bibigrid_file_stat

    - name: Change group ownership of OpenStack credentials file to slurm
      file:
        path: /etc/openstack/clouds.yaml
        group: slurm
        mode: "0o640"  # (owner can read/write, group can read, others have no access)
      when: bibigrid_file_stat.stat.exists

- name: Create slurm db
  mysql_db:
    name: "{{ slurm_conf.db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create slurm db user
  mysql_user:
    name: "{{ slurm_conf.db_user }}"
    password: "{{ slurm_conf.db_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create slurmdb configuration file
  template:
    src: slurm/slurmdbd.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: root
    mode: "0o600"

- name: Generate random JWT Secret
  command:
    cmd: "dd if=/dev/random of=/etc/slurm/jwt-secret.key bs=32 count=1"
    creates: "/etc/slurm/jwt-secret.key" # only run the command when file is not present

- name: Change file Properties of JWT Secret file
  file:
    path: /etc/slurm/jwt-secret.key
    owner: slurm
    group: slurm
    mode: "0o600"

- name: Copy env file for configuration of slurmrestd
  copy:
    src: slurm/default/slurmrestd
    dest: /etc/default/slurmrestd
    owner: root
    group: root
    mode: "0o644"

- name: Create system overrides directories (slurmdbdm slurmrestd)
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    group: root
    owner: root
    mode: "0o755"
    state: directory
  with_items:
    - slurmdbd
    - slurmrestd

- name: Copy system overrides (slurmdbdm slurmrestd)
  copy:
    src: "slurm/systemd/{{ item }}.override"
    dest: "/etc/systemd/system/{{ item }}.service.d/override.conf"
    mode: "0o644"
    owner: root
    group: root
  with_items:
    - slurmdbd
    - slurmrestd

- name: Register Slurm users home dir
  shell: "set -o pipefail &&  grep slurm /etc/passwd | cut -d ':' -f 6"
  register: bibigrid_slurm_home
  changed_when: false
  args:
    executable: bash

- name: Change mode of /opt/slurm directory
  file:
    owner: slurm
    group: ansible
    path: /opt/slurm/
    state: directory
    mode: "0o770"

- name: Ensures /etc/slurm dir exists
  file:
    path: /etc/slurm/
    state: directory
    mode: "0o755"

- name: Ensures /opt/slurm/.ssh/ dir exists
  file:
    path: /opt/slurm/.ssh/
    group: slurm
    owner: slurm
    state: directory
    mode: "0o700"

- name: Copy private key (openstack keypair)
  copy:
    src: ~/.ssh/id_ecdsa
    dest: /opt/slurm/.ssh/id_ecdsa
    owner: slurm
    group: slurm
    mode: "0o600"

- name: Copy create program script (power)
  copy:
    src: slurm/create.sh
    dest: /opt/slurm/create.sh
    owner: slurm
    group: ansible
    mode: "0o550"

- name: Copy terminate program script (power)
  copy:
    src: slurm/terminate.sh
    dest: /opt/slurm/terminate.sh
    owner: slurm
    group: ansible
    mode: "0o550"

- name: Copy fail program script (power)
  copy:
    src: slurm/fail.sh
    dest: /opt/slurm/fail.sh
    owner: slurm
    group: ansible
    mode: "0o550"

- name: Copy "create_server.py" script
  copy:
    src: slurm/create_server.py
    dest: /usr/local/bin/create_server.py
    owner: slurm
    group: ansible
    mode: "0o750"

- name: Copy "delete_server.py" script
  copy:
    src: slurm/delete_server.py
    dest: /usr/local/bin/delete_server.py
    owner: slurm
    group: ansible
    mode: "0o750"

- name: Install python dependencies
  ansible.builtin.pip:
    name:
      - python-openstackclient==6.0.0
      - openstacksdk==0.62.0
      - os_client_config
      - filelock
      - paramiko
      - ansible-runner
      - pyzabbix
    virtualenv: /opt/bibigrid-venv

- name: 'Add default user to ansible group'
  user:
    name: '{{ ssh_user }}'
    append: true
    groups:
      - ansible

- name: Generate location specific worker userdata
  template:
    src: slurm/worker_userdata.j2
    dest: "/opt/slurm/userdata_{{ hostvars[item].cloud_identifier }}.txt"
    owner: slurm
    group: ansible
    mode: "0o640"
  with_items: "{{ groups.vpngtw + groups.master }}"

- name: Enable slurmdbd and slurmrestd services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: started
    daemon_reload: true
  with_items:
    - slurmdbd
    - slurmrestd

- name: Enable slurmctld service
  systemd:
    name: "slurmctld"
    enabled: true
    masked: false
    state: started
    daemon_reload: true


- when: bibigrid_slurm_home.stdout != '/opt/slurm'
  block:
    - name: Stop Slurm Services
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - slurmctld
        - slurmd
        - slurmdbd
        - slurmrestd
    - name: Add slurm user to ansible and give slurm user a home
      user:
        name: slurm
        append: true
        create_home: true
        groups:
          - ansible
        home: /opt/slurm
        shell: /bin/false
    - name: Start Slurm Services
      systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - slurmctld
        - slurmd
        - slurmdbd
        - slurmrestd

- name: Restart Slurm services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - slurmdbd
    - slurmrestd
    - slurmctld
    - slurmd
