- name: Deactivate auto-update function
  shell: |
        systemctl stop apt-daily.service
        systemctl disable apt-daily.service
        systemctl stop apt-daily.timer
        systemctl disable apt-daily.timer
        systemctl kill --kill-who=all apt-daily.service
        while ! (systemctl list-units --all apt-daily.service | fgrep -q dead)
        do
          sleep 1;
        done

- name: Install common packages
  apt:
    name: ["apt-transport-https","ca-certificates","curl","software-properties-common"]
    state: "present"

- name: Install OpenStack object store client
  apt:
    name: "swift"
    state: "present"
  when: mode == "openstack"

# https://cloud.google.com/storage/docs/gsutil_install?hl=de#deb
- name: Add Google Compute repository key
  shell: 'curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -'
  when: mode == "googlecloud"

- name: Add Google Compute repositories
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_lsb.codename }} main"
    state: present
  when: mode == "googlecloud"

- name: Update apt cache for Google Compute
  apt:
    update_cache: 'yes'

- name: Install Google Compute object store client
  apt:
    name: "google-cloud-sdk"
    state: "present"
  when: mode == "googlecloud"

# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
- name: Add Azure repository key
  apt_key:
    id: 52E16F86FEE04B979B07E28DB02C46DF417A0893
    keyserver: packages.microsoft.com
    state: present
  when: mode == "azure"

- name: Add new Azure repository key
  shell: 'curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -'
  when: mode == "azure"

- name: Add Azure repositories
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_lsb.codename }} main"
    state: present
  when: mode == "azure"

- name: Update apt cache for Azure
  apt:
    update_cache: 'yes'

- name: Install Azure object store client
  apt:
    name: "azure-cli"
    state: "present"
  when: mode == "azure"

# https://docs.aws.amazon.com/cli/latest/userguide/installing.html
- name: Install AWS object store client
  pip:
    name: awscli
    extra_args: --upgrade --user
  when: mode == "aws"

# - name: Add Mesosphere project key
#   apt_key:
#     id: E56151BF
#     keyserver: keyserver.ubuntu.com
#     state: present

# - name: Add Mesosphere repositories
#   apt_repository:
#     repo: "deb-src http://repos.mesosphere.io/ubuntu {{ ansible_lsb.codename }} main"
#     state: present


- name: Add Docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename}} stable
    state: present

- name: Add Cassandra repository key
  apt_key:
    url: https://www.apache.org/dist/cassandra/KEYS
    state: present
    
- name: Add Cassandra repository
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 311x main
    state: present


- name: Update apt cache
  apt:
    update_cache: 'yes'


- name: Install pip
  apt:
    name: pip
    state: latest