- name: Copy bibigrid performance script
  copy:
    src: bibigridperf.py
    dest: /usr/local/bin/bibigridperf
    mode: 0755
    owner: root
    group: root

#- name: Execute bibigrid performance script
#  shell: '/usr/local/bin/bibigridperf'
#  args:
#    chdir: '~/'

# TODO: make results available
