- name: Install NFS server package
  apt:
    name: "nfs-kernel-server"
    state: "latest"

- name: Create export directories
  file:
    path: "{{ item.src }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
      - "{{ nfs_mounts }}"

- name: Configure nfs exports
  lineinfile:
    path: /etc/exports
    state: present
    regexp: '^{{ item.src }}'
    line: '{{ item.src }} {{ CIDR }}(rw,nohide,insecure,no_subtree_check,async)'
  with_items:
    - "{{ nfs_mounts }}"
  register: nfs_exports

- name: Restart NFS server (on config change)
  systemd:
    name: nfs-kernel-server
    state: restarted
  when:
    - nfs_exports | changed




