

- name: Install mesosphere meta package ( includes the zookeeper, mesos, marathon, and chronos )
  apt:
    name: "mesosphere"
    state: present  # not using latest package to avoid time consuming checks for prepared images


# Configuration see https://www.digitalocean.com/community/tutorials/how-to-configure-a-production-ready-mesosphere-cluster-on-ubuntu-14-04

- name:  Start/Enable zookeeper
  systemd:
      name: zookeeper
      state: started
      enabled: yes

- name: Create mesos spooldir
  file:
      path: /vol/spool/mesos
      state: directory
      owner: root
      group: root
      mode: 0777

- name: Configure mesos master
  copy:
    content: bibigrid
    dest: /etc/mesos-master/cluster
    owner: root
    group: root
    mode: 0644
  copy:
    content: "{{ master.ip }}"
    dest: /etc/mesos-master/ip
    owner: root
    group: root
    mode: 0644
  copy:
    content: /vol/spool/mesos
    dest: /etc/mesos-master/work_dir
    owner: root
    group: root
    mode: 0644
  copy:
    content: zk://{{ master.ip }}:2181/mesos
    dest: /etc/mesos/zk
    owner: root
    group: root
    mode: 0644

- name: Start mesos master
  systemd:
        name: mesos-master
        state: started
        enabled: yes

- block:
  - name: Configure master as mesos slave
    copy:
      content: /vol/spool/mesos
      dest: /etc/mesos-slave/work_dir
      owner: root
      group: root
      mode: 0644

    copy:
      content: mesos,docker
      dest: /etc/mesos/zk
      owner: root
      group: root
      mode: 0644

    copy:
      content: false
      dest: /etc/mesos-slave/switch_user
      owner: root
      group: root
      mode: 0644

  - name: Start mesos slave
    systemd:
      name: mesos-slave
      state: started
      enabled: yes

  when: use_master_as_compute == 'yes'
